# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: qzwlecr
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 0
          plugin_languages_recent.load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes

          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          plugin_habits: yes
          plugin_habits_days: 0
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_trim: yes

          config_display: large

